### ISSUE TITLE
Calendar Not Updated

### ISSUE THREAD

**Issue by Minnett** [alexfaber2011/duluthalternatesideparking.com#1]
Hello,

It currently doesn't account for transition period, but you could use the following JS from the city site instead of hard coding the calendar. It uses a starting date of Jan. 5, 2014 at the changeover time of 8:00 pm to calculate the side.

`function dateTest(todaysDate){
  var initialDate = new Date(2014, 0, 5, 20, 0, 0, 0);
  var initialSide = "EVEN";

  var milDifference = todaysDate.getTime() - initialDate.getTime();
  var daysDifference = Math.ceil(milDifference / 1000 / 60 / 60 / 24);
  var weekNumber = Math.ceil(daysDifference / 7);

  if (weekNumber % 2 == 1) {
    console.log("ODD");
  }
  else {
    console.log("EVEN");
  }
}

dateTest(new Date());

dateTest(new Date(2022,10,27,23,0,0,0));

dateTest(new Date(2022,10,27,14,0,0,0));`

**Comment by alexfaber2011** [comment]
Hello @Minnett and thanks for offering some code!  As coded, the transition period is accounted for, but perhaps it's not working as intended?

**Comment by alexfaber2011** [comment]
Here's the section of code that handles the transition: https://github.com/alexfaber2011/duluthalternatesideparking.com/blob/main/index.js#L47-L59
